[package]
name = "pmtree"
version = "1.0.0"
edition = "2021"

[dev-dependencies]
hex-literal = "0.3.4"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
sled = "0.34.7"
rln = { git = "https://github.com/vacp2p/zerokit", rev = "490206a" }
ark-serialize = "0.3.0"

[dependencies]
async-recursion = "1.0.4"
async-trait = "0.1.71"
rayon = { version = "1.6.1", optional =  false }
tokio = { version = "1.29.1", features = ["full"] }
